apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cluster-gen
  name: cluster-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-gen
  template:
    metadata:
      labels:
        app: cluster-gen
    spec:
      containers:
      - image: {{ .Values.image }}
        name: cluster-gen
        ports:
        - containerPort: 3000
