# get latest tag
# create github release
# build container
# push the docker image to registry.scs.community

name: release-builder
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get latest tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          LATEST_RELEASE: ${{ steps.vars.outputs.tag }}
        run: |
          echo $LATEST_RELEASE
      - name: Release
        uses: softprops/action-gh-release@v2
  build-container:
    runs-on: ubuntu-latest
    container: docker
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t cluster-gen .
