name: release-and-build
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}
          generate_release_notes: true
          make_latest: true
  build:
    runs-on: ubuntu-latest
    container: docker
    steps:
      - uses: actions/checkout@v4
        name: Build and push docker image
      - run: |
          docker build . -t registry.scs.community/cluster-gen/cluster-gen:${{ github.ref_name }}
          docker login registry.scs.community -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_TOKEN }}
          docker push registry.scs.community/cluster-gen/cluster-gen:${{ github.ref_name }}
